### PR TITLE
clean up find_lenses, get geometry_file from namelist

### PR DESCRIPTION
**Pull request by lstagner**
Couldn't get the imaging to work it looks like you were in between changes.

### CODE REVIEW

**Comment by Nathan-Bolte** [comment]
@lstagner Imaging works. Make sure to pull. Make sure your LOS have a single lens and spread out in 2D. There's no test for these conditions, it should just fail. The D3D case you gave me works, known as 159243L01 / 791 / or npatest. Something's strange if it still doesn't work, so let me know.

**Comment by lstagner** [comment]
This is the error I'm getting when I am trying to plot an image
```
  File "/home/lstagner/anaconda3/lib/python3.5/tkinter/__init__.py", line 1549, in __call__
    return self.func(*args)
  File "./fidaviewer.py", line 1310, in <lambda>
    command = (lambda: self.spec.plot_spec_image(self.fig, self.canvas))).pack(side = tk.TOP, expand = tk.Y, fill = tk.BOTH)
  File "./fidaviewer.py", line 475, in plot_spec_image
    spec = integrate.simps(spec[:, w], x = self.lam[w], axis = 1)  # (this_nchan)
IndexError: too many indices for array
```
This is using this branch and an updated version of 159243L01 that I uploaded to google drive

**Comment by Nathan-Bolte** [comment]
@lstagner Please take a look at the spectra and the geometry h5 files. Notice that spectra.h5/nchan is 53 while geometry/spec/nchan is 33. This is what is causing the (different) error that I get with that example. How is this possible?

**Comment by lstagner** [comment]
If you look at the namelist file you will see that the geometry file is`210rt_geometry.h5` which does have 53 chords. If you look at this PR you will notice I changed how geometry file is loaded since it is an input file and not an output file and does not necessarily follow the `[runid]_...` pattern.

**Pull request merged**
