### PR TITLE
ask for namelist file instead of directory

### PR DESCRIPTION
**Pull request by lstagner**
Its common to have various time slices in the same directory so this makes the GUI ask for the namelist file instead of the directory.

### CODE REVIEW

**Review by Nathan-Bolte — APPROVED** [review]
Nice changes. Solves mult file problem

**Comment by danfulton** [comment]
Am I signed up for notifications on this project ??!?!!?!??!?!

**Comment by lstagner** [comment]
This is the project from Kirby's software development class so the whole class is getting notifications. I suggest you unsubscribe

**Comment by danfulton** [comment]
That's pretty hilarious, actually.

**Pull request merged**
